changed WirelessPhy::node to return a Node instead of a MobileNode in order to fix following error message in Visual C++ on Windows
./mac\wireless-phy.h(75) : error C2555: 'WirelessPhy::node' : overriding virtual function differs from 'Phy::node' only by return type or calling convention
         ./mac\phy.h(71) : see declaration of 'Phy'